name: myapp
description: A exported flutter project from FUNCTION12


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  otp_text_field: ^1.1.3
  flutter_rating_bar: ^4.0.1
  flutter_side_menu: ^0.3.2
  timer_count_down: ^2.2.2
  pin_code_fields: ^7.4.0
  form_validator: ^2.1.1
  flutter_bloc: ^8.1.2
  custom_text_field: ^0.0.3
  blur: ^3.0.0
  google_maps_flutter: ^2.2.6
  flutter_map: ^4.0.0
  firebase_core: ^2.13.0
  get: ^4.6.5
  firebase_auth: ^4.6.1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.1.1
  firebase_database: ^10.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
