// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL54CGNUzPk0RwR6ngaQFi2Lm3s7secCM',
    appId: '1:896707340050:android:fed7d7ba1348d9710035cb',
    messagingSenderId: '896707340050',
    projectId: 'ride-ease-71787',
    databaseURL: 'https://ride-ease-71787-default-rtdb.firebaseio.com',
    storageBucket: 'ride-ease-71787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdP5Le1xrflFvJCkvKD89im7sUN6tnxA',
    appId: '1:896707340050:ios:b9437e770b860c980035cb',
    messagingSenderId: '896707340050',
    projectId: 'ride-ease-71787',
    databaseURL: 'https://ride-ease-71787-default-rtdb.firebaseio.com',
    storageBucket: 'ride-ease-71787.appspot.com',
    iosClientId: '896707340050-79mmmn2dmtcl9o39rl9o8alie2qkndd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
